### ISSUE TITLE
ReferenceError: Crawler is not defined

### ISSUE THREAD

**Issue by sirshurak** [JefferyHus/es6-crawler-detect#39]
I have a project build with create-react-app and there's a SSR with express to identify crawlers and render the React site

```
evalmachine.<anonymous>:1
new Crawler(req)
^

ReferenceError: Crawler is not defined
    at evalmachine.<anonymous>:1:1
    at Script.runInThisContext (node:vm:129:12)
    at middleware (C:\Users\Vinicius Tonelli\Documents\GitHub\nwsite\node_modules\es6-crawler-detect\src\index.js:8:37)
    at Layer.handle [as handle_request] (C:\Users\Vinicius Tonelli\Documents\GitHub\nwsite\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Vinicius Tonelli\Documents\GitHub\nwsite\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Vinicius Tonelli\Documents\GitHub\nwsite\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Vinicius Tonelli\Documents\GitHub\nwsite\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Vinicius Tonelli\Documents\GitHub\nwsite\node_modules\express\lib\router\index.js:275:10)
    at cors (C:\Users\Vinicius Tonelli\Documents\GitHub\nwsite\node_modules\cors\lib\index.js:188:7)
    at C:\Users\Vinicius Tonelli\Documents\GitHub\nwsite\node_modules\cors\lib\index.js:224:17
```

This issue occurs on version 3.1.3

Currently I've downgrade to version 3.1.2

### Versions
**Node**: 15.8.0 and 16.3.0 (both same results)
**express**: 4.17.1
**es6-crawler-detect**: 3.1.3
**react**: 16.14.0

**Comment by JefferyHus** [comment]
Thanks for flagging. Can you please drop some details about which Node.js version are you using?

**Comment by sirshurak** [comment]
> Thanks for flagging. Can you please drop some details about which Node.js version are you using?

Updated with node versions
